name: Dhisa Forwarder System

on:
  schedule:
    - cron: '0 */6 * * *' # Jalan otomatis setiap 6 jam
  workflow_dispatch:      # Tombol manual "Run Workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install telethon pytz

      - name: Run Dhisa Forwarder
        run: python dhisa_forward.py

      - name: Simpan Progres (Update Last ID)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_id.txt
          git commit -m "Dhisa Update: Progres Terakhir [skip ci]" || echo "Tidak ada perubahan"
          git push
